- hosts: nodes
  tasks:

    - name: Kill Existing Node Engine 
      shell: kill -9 $(ps -ax | grep NodeEngine | sed 's/|/ /' | awk '{print $1}')
      become: true
      ignore_errors: true

    - name: Kill Existing Net Manager
      shell: kill -9 $(ps -ax | grep NetManager | sed 's/|/ /' | awk '{print $1}')
      become: true
      ignore_errors: true

