- hosts: root
  tasks:
    - name: Kill Root and Cluster Components if 1-DOC mode 
      shell: cd oakestra/run-a-cluster ; sudo -E docker compose -f 1-DOC.yaml kill  

- hosts: root
  tasks:
    - name: Kill Root 
      shell: cd oakestra/root_orchestrator ; sudo -E docker compose kill

- hosts: cluster
  tasks:
    - name: Kill Cluster
      shell: cd oakestra/cluster_orchestrator ; sudo -E docker compose kill
