- hosts: root
  tasks:

    - name: Clone Oak Repo
      shell: git clone https://github.com/oakestra/oakestra.git
      ignore_errors: true

    - name: Run Root and Cluster Components in 1-DOC mode 
      environment:
        CLUSTER_NAME: '{{ clusterName }}'
        CLUSTER_LOCATION: '{{ clusterLocation }}'
        SYSTEM_MANAGER_URL: '{{ rootIP }}'  
      shell: cd oakestra ; sudo -E docker compose -f run-a-cluster/1-DOC.yaml -f run-a-cluster/override-alpha-versions.yaml up --detach  

